name: Run Selenium Tests & Email Allure Report (Windows)

on:
  schedule:
    - cron: '0 14 * * 1-5' # 7:30 PM IST (2:00 PM UTC), Mon–Fri
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Maven
        uses: s4u/setup-maven-action@v1.9.0
        with:
          maven-version: '3.9.5'

      - name: Debug - List files
        run: Get-ChildItem -Recurse

      - name: Build with Maven and run tests
        run: mvn clean test

      - name: Verify and Copy allure-results to target
        run: |
          if (Test-Path "target/allure-results") {
            Write-Host "✅ Allure results found in root. Copying to target..."
            New-Item -ItemType Directory -Force -Path "target\allure-results"
            Copy-Item -Path "allure-results\*" -Destination "target/allure-results" -Recurse -Force
          } else {
            Write-Host "❌ Allure results NOT found."
            exit 1
          }

      - name: Generate Allure Report
        run: |
          mvn io.qameta.allure:allure-maven:2.11.2:report ^
            -Dallure.results.directory=target/allure-results ^
            -Dallure.report.directory=target/allure-report
        shell: cmd

      - name: Debug - Show Allure Report files
        run: |
          if (Test-Path "target/allure-report") {
            Write-Host "✅ Allure report generated:"
            Get-ChildItem -Recurse target/allure-report
          } else {
            Write-Host "❌ Allure report NOT generated."
            exit 1
          }

      - name: Archive Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report/

  deploy:
    needs: test
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Allure Report
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: site

      - name: Create index.html redirect for GitHub Pages
        run: |
          echo '<meta http-equiv="refresh" content="0; url=index.html" />' > site/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site

  notify:
    needs: deploy
    runs-on: windows-latest

    steps:
      - name: Send Email with Report Link Only
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Selenium Automation Report
          to: 006qatest@gmail.com
          from: GitHub CI Bot <005qatest@gmail.com>
          body: |
            Hello,

            Your automated Selenium test report has been successfully generated and deployed.

            📄 View the full HTML report here:
            🔗 https://shubhamkohli2002.github.io/Login-Verification/

            Regards,  
            GitHub Actions Bot
